# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd backend
    yarn
    yarn global add serverless
    cp .env.template .env  
    npx sls config credentials --provider aws --key $(keyId) --secret $(accessKey) 

    sudo chmod +x scripts/serverless
    sudo chmod +x scripts/build
    sudo chmod +x scripts/generate-cache
    sudo chmod +x scripts/bundle
    sudo chmod +x .env
    sudo apt-get install zip
    sudo yarn deploy
    cd ..
    cd clientapp
    sudo npm install
    npm run build
  env: {
        AWS_ACCESS_KEY_ID: $(keyId),
        AWS_SECRET_ACCESS_KEY: $(accessKey)

  }
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/clientapp/build'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1