# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    sudo apt-get update
    sudo apt-get install -y default-jre 
    cd backend
    yarn
    yarn global add serverless
    yarn global add firebase-tools
    yarn exec sls config credentials --provider aws --key $(keyId) --secret $(accessKey) 
    yarn exec sls dynamodb install
    yarn exec sls offline start
    yarn exec sls deploy
    cd ..
  env: {
        AWS_ACCESS_KEY_ID: $(keyId),
        AWS_SECRET_ACCESS_KEY: $(accessKey)

  }
  displayName: Backend

- script: |
    cd clientapp
    yarn
    yarn build
    yarn exec firebase deploy --token "$(FIREBASE_DEPLOY_KEY)" --non-interactive
  displayName: Clientapp

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '$(System.DefaultWorkingDirectory)/backend/tests/result/junit.xml'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/backend/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/backend/coverage'