# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd backend
    yarn
    cp .env.template .env
    export 'AWS_ACCESS_KEY_ID=$(keyId)'
    export 'AWS_SECRET_ACCESS_KEY=$(accessKey)'
    sudo chmod +x scripts/serverless
    sudo chmod +x scripts/build
    sudo chmod +x scripts/generate-cache
    sudo chmod +x scripts/bundle
    sudo chmod +x .env
    sudo yarn deploy
    cd ..
    cd clientapp
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/clientapp/build'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1