#serverless.yml
service: SailingWeb
provider: 
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: BoatData
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:ScanItem
        - dynamodb:DeleteItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    SailingWeb:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: boatName
            AttributeType: S
          - AttributeName: crew
            AttributeType: N
        KeySchema:
          - AttributeName: boatName
            KeyType: HASH
          - AttributeName: crew
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        
plugins:
  - serverless-webpack

custom: 
  webpack:
    includeModules: true

functions:
  query:
    handler: src/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true