#serverless.yml
service: SailingWeb
provider: 
  name: aws
  runtime: nodejs8.10
  environment:
  role: arn:aws:iam::118983564982:role/sailingweb
    
resources:
  Resources:
    BoatData:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: boatName
            AttributeType: S
          - AttributeName: crew
            AttributeType: N
        KeySchema:
          - AttributeName: boatName
            KeyType: HASH
          - AttributeName: crew
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: BoatData
    Events:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Events
    SignOn:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: SignOn
        
plugins:
  - serverless-webpack

custom: 
  webpack:
    includeModules: true

functions:
  query:
    handler: src/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true