#serverless.yml
service: SailingWeb
provider: 
  name: aws
  runtime: nodejs8.10
  environment:
  role: arn:aws:iam::118983564982:role/sailingweb
    
resources:
  Resources:
    BoatData:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: boatName
            AttributeType: S
          - AttributeName: crew
            AttributeType: N
        KeySchema:
          - AttributeName: boatName
            KeyType: HASH
          - AttributeName: crew
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: BoatData
    Races:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
          - AttributeName: type_id
            AttributeType: S
          - AttributeName: eventTimeStamp
            AttributeType: N
        LocalSecondaryIndexes:
          - IndexName: eventId-eventTimeStamp-index
            KeySchema: 
              - AttributeName: eventId
                KeyType: HASH
              - AttributeName: eventTimeStamp
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
          - AttributeName: type_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Races
        
plugins:
  - serverless-webpack
  - serverless-jest-plugin
  - serverless-dynamodb-local
  - serverless-offline
custom: 
  dynamodb: 
    start:
      port: 8000
      inMemory: true
      migrate: true
  webpack:
    webpackConfig: './webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'yarn'   # Packager that will be used to package your external modules
  jest:
    # You can pass jest options here
    # See details here: https://facebook.github.io/jest/docs/configuration.html
    # For instance, uncomment next line to enable code coverage
    collectCoverage: true
functions:
  query:
    handler: src/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true