#serverless.yml
service: lukes-epic-graphql-dynamodb-api
provider: 
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: BoatData
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    NicknamesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: BoatName
            AttributeType: S
          - AttributeName: Crew
            AttributeType: N
        KeySchema:
          - AttributeName: BoatName
            KeyType: HASH
          - AttributeName: Crew
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: BoatData
        
plugins:
  - serverless-webpack

custom: 
  webpack:
    includeModules: true

functions:
  query:
    handler: src/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true