'use strict';

// tests for query
// Generated by serverless-jest-plugin

const mod = require('./../src/graphql');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'graphqlHandler' });

describe('query', () => {
  beforeAll((done) => {
  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      expect(response).toBeDefined();
    });
  });
});
