# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

        # yarn exec sls config credentials --provider aws --key "$keyId" --secret "$accessKey"
      - name: Backend
        shell: bash
        env: 
          keyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          accessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          sudo apt update
          sudo apt install -y default-jre 
          cd backend
          yarn
          yarn global add serverless
          yarn global add firebase-tools
          yarn exec serverless dynamodb install
          yarn exec serverless offline start
          yarn exec serverless deploy
          cd ..

          

      - name: Clientapp
        run: |
          cd clientapp
          yarn
          yarn build
          npx firebase-tools deploy --token "$(FIREBASE_DEPLOY_KEY)" --non-interactive

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
